package carrerasautosconhilos;

import javax.swing.JLabel;

/**
 *
 * @author Asus
 */
public class PistaCarreraAutosHilos extends javax.swing.JFrame {

    public PistaCarreraAutosHilos() {
        initComponents();
        this.setTitle("CARRERA DE AUTOS CON HILOS"); // Ponemos el titulo en el JFrame
        this.setLocationRelativeTo(null); // Es para centrar el JFrame
    }

    public JLabel getlbl1() {
        return lblAuto1;
    }

    public JLabel getlbl2() {
        return lblAuto2;
    }
    public JLabel getlbl3() {
        return lblAuto3;
    }
    public JLabel getlbl4() {
        return lblAuto4;
    }
    public JLabel getlbl_Llegada() {
        return lblLlegada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblAuto1 = new javax.swing.JLabel();
        lblAuto2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAuto3 = new javax.swing.JLabel();
        lblAuto4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLlegada = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnIniciarJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAuto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.gif"))); // NOI18N
        lblAuto1.setText("jLabel4");
        jPanel1.add(lblAuto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 40));

        lblAuto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.gif"))); // NOI18N
        jPanel1.add(lblAuto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pista.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 1080, 210));

        lblAuto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.gif"))); // NOI18N
        jPanel1.add(lblAuto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 100, -1));

        lblAuto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/auto.gif"))); // NOI18N
        jPanel1.add(lblAuto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pista.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 1080, 200));

        lblLlegada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llegada.jpg"))); // NOI18N
        jPanel1.add(lblLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 140, 150, 410));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publicoo.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 630, 150));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publicoo.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 550, 620, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publico.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publico.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 620, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 430));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publico.jpg"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/publicoo.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 620, 130));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1400, 690));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PISTA DE CARRERAS DE AUTOS CON HILOS");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 820));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarJuego.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIniciarJuego.setText("INICIAR CARRERA AHORA");
        btnIniciarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarJuegoActionPerformed(evt);
            }
        });
        jPanel3.add(btnIniciarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 820, 1420, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarJuegoActionPerformed
        // TODO add your handling code here:

        lblAuto1.setLocation(0, lblAuto1.getLocation().y);
        lblAuto2.setLocation(0, lblAuto2.getLocation().y);
        lblAuto3.setLocation(0, lblAuto3.getLocation().y);
        lblAuto4.setLocation(0, lblAuto4.getLocation().y);
        
        //Se crea una instancia de la subclase CarrerasAutosConHilos con new
        //Se ejecuta cada hilo son start()
        CarrerasAutosConHilos hilo1 = new CarrerasAutosConHilos(lblAuto1, this);
        CarrerasAutosConHilos hilo2 = new CarrerasAutosConHilos(lblAuto2, this);
        CarrerasAutosConHilos hilo3 = new CarrerasAutosConHilos(lblAuto3, this);
        CarrerasAutosConHilos hilo4 = new CarrerasAutosConHilos(lblAuto4, this);
        hilo1.start();
        hilo2.start();
        hilo3.start();
        hilo4.start();

    }//GEN-LAST:event_btnIniciarJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PistaCarreraAutosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PistaCarreraAutosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PistaCarreraAutosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PistaCarreraAutosHilos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PistaCarreraAutosHilos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAuto1;
    private javax.swing.JLabel lblAuto2;
    private javax.swing.JLabel lblAuto3;
    private javax.swing.JLabel lblAuto4;
    private javax.swing.JLabel lblLlegada;
    // End of variables declaration//GEN-END:variables
}
